"""add column limit

Revision ID: ad9acf5ba3ed
Revises: 
Create Date: 2023-04-14 12:14:16.169153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9acf5ba3ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False, comment='Цена в копейках'),
    sa.Column('day_limit', sa.Integer(), nullable=False, comment='Дневной лимит сообщений'),
    sa.PrimaryKeyConstraint('id'),
    comment='тарифы'
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Роль юзера'
    )
    op.create_table('wa_client_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Статус аккаунта WA'
    )
    op.create_table('wa_client_workes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Чем занят аккаунт WA'
    )
    op.create_table('wa_mailing_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='статус wa рассылки'
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('sphere', sa.String(length=150), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('bot_usage', sa.String(length=150), nullable=True),
    sa.Column('where_from', sa.String(length=150), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Юзеры'
    )
    op.create_table('nps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=500), nullable=True),
    sa.Column('mark', sa.String(length=5), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='nps клиентов'
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tariff', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tariff'], ['tariff.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='платежи'
    )
    op.create_table('user_tariff',
    sa.Column('tariff', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tariff'], ['tariff.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tariff', 'user_id')
    )
    op.create_table('wa_client_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('id_instance', sa.String(length=100), nullable=False),
    sa.Column('api_token', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('count_check', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['wa_client_statuses.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['wa_client_workes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Аккаунты whatsapp'
    )
    op.create_table('wa_mailing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator', sa.String(length=20), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('send', sa.Integer(), nullable=False, comment='сколько сообщений отправлено'),
    sa.Column('for_sending', sa.Integer(), nullable=False, comment='сколько надо отправить'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['wa_mailing_statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='рассылки whatsapp'
    )
    op.create_table('wa_mailing_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailing_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('is_send', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mailing_id'], ['wa_mailing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='номера для рассылок'
    )
    op.execute("INSERT INTO tariff VALUES (1,'Бесплатный', 'free', 0, 20),(2,'Эффективный', 'effective', 130000, 2000),(3,'Все включено', 'allin', 900000, 5000)")
    op.execute("INSERT INTO user_role VALUES (10,'admin'),(5,'pending'),(2, 'user')")
    op.execute("INSERT INTO wa_client_statuses VALUES (1,'authorized'),(3,'banned'),(2,'waiting_for_authorization')")
    op.execute("INSERT INTO wa_client_workes VALUES (2,'checking'),(1,'unworking'),(3,'mailing')")
    op.execute("INSERT INTO wa_mailing_statuses VALUES (1,'unworking'),(2,'working'),(3,'finished'),(4,'paused')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wa_mailing_phones')
    op.drop_table('wa_mailing')
    op.drop_table('wa_client_accounts')
    op.drop_table('user_tariff')
    op.drop_table('payments')
    op.drop_table('nps')
    op.drop_table('users')
    op.drop_table('wa_mailing_statuses')
    op.drop_table('wa_client_workes')
    op.drop_table('wa_client_statuses')
    op.drop_table('user_role')
    op.drop_table('tariff')
    # ### end Alembic commands ###
